---
title: "Distributions of fiscal income in French regions, 1960-2018"
other-lang-href: /fr/research/publications.html
author: "F. Bonnet and A. Sotura"
date: "2021"
venue: "Working Paper"
status: "Permanent working Paper"
categories: [working-paper]
---

[**Working Paper**]{.status-tag}

\[[Banque de France](https://publications.banque-france.fr/en/regional-income-distributions-france1960-2018)\]

> *This paper proposes homogeneous annual series on the income distribution of French metropolitan départements for the period 1960-69 and 1986-2018. We rely on unpublished and newly digitised archives of the French Ministry of Finance. They consist of fiscal tabulations that are a summary of households’ income tax declarations. Based on these raw sources, we interpolate the whole income distribution of French metropolitan départements after 1986. Before 1986, we need more assumptions as only households liable to French income tax filed income tax declarations at that time. We propose a methodology to estimate the number and average income of non-taxable households before 1986 that also allows us to reconstruct the income distribution of French metropolitan départements for the period 1960-69.*
