---
title: "Estimating Subnational Excess Mortality in Times of Pandemic. An application to French départements in 2020"
other-lang-href: /fr/research/publications.html
author: "F. Bonnet and C.-G. Camarda"
date: "2024"
venue: "PLoS ONE"
status: "Published"
categories: [published]
---

[***PLoS ONE***]{.journal}

\[[Article](https://doi.org/10.1371/journal.pone.0293752)\] · \[[Replication kit](https://osf.io/zt2c8/)\]

> *The Covid-19 pandemic did not affect sub-national regions in a uniform way. Knowledge of the impact of the pandemic on mortality at the local level is therefore an important issue for better assessing its burden. Vital statistics are now available for an increasing number of countries for 2020 and 2021, and allow the calculation of sub-national excess mortality. However, this calculation faces two important methodological challenges: (1) it requires appropriate mortality projection models; (2) small populations implies important uncertainty in the estimates, commonly neglected. We address both issues by adopting a method to forecast mortality at sub-national level and by incorporating uncertainty in the computation of mortality measures. We illustrate our approach to French départements (NUTS 3, 95 geographical units) and produce estimates for 2020 and both sexes. Nonetheless, the proposed approach is so flexibility to allow estimation of excess mortality during Covid-19 in most demographic scenarios as well as for past pandemics.*
