---
title: "Life and Death in a Changing City: Mortality Patterns and Inequalities in Paris, 1890–1949"
author: "F. Bonnet, C. Torres, L. Kesztenbaum and F. Meslé"
date: "2025"
venue: "Population and Development Review"
status: "Published"
categories: [published]
---

[***Population and Development Review***]{.journal}

\[[Article](https://onlinelibrary.wiley.com/share/author/WN43ISQ8YTSGVTI3U6WJ?target=10.1111/padr.70031)\] · \[[Code & data (OSF)](https://osf.io/wcyft/)\] · \[[Shiny app](https://mortalidad-pp.shinyapps.io/suppl_results_mortality_cod_paris/)\] · \[[Media coverage](../../media.qmd)\]

> *Over the past two centuries, European metropolises transformed from urban graveyards to healthy cocoons. Despite its critical role in the history of longevity, this evolution remains underexplored due to limited detailed data. We leverage a newly harmonized dataset of high-quality, cause-specific mortality records to examine the rapid increase in life expectancy in Paris during the first half of the 20th century. During this period, Paris' life expectancy converged with that of the rest of France. Using a consistent cause-of-death classification from 1890 to 1949, we show that infectious diseases—particularly tuberculosis and respiratory infections—accounted for 60–70% in the 25-year gain in life expectancy at age 1, with mortality reductions among children and young adults driving most of these improvements. We also document a profound shift in the causes behind the sex gap in life expectancy, from infectious diseases to cardiovascular and cancer-related causes. Furthermore, our analysis of cause-specific and socio-economic data for Paris's 80 neighborhoods reveals pronounced social gradients in infectious mortality, with the poorest areas suffering the highest rates. These disparities widened during the early phase of the tuberculosis mortality decline, favoring wealthier areas, but narrowed in subsequent phases as public health improvements reached poorer neighborhoods.*
